nelmio_api_doc:
    documentation:
        info:
            title: Documentation of the BileMo API
            description: Products and users management
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/products
            - ^/users
            - ^/clients
            - ^/login
